updated azure
Anjugeorg-e/Vonnue_training pull request #3
Opened 2023-02-14 17:00 UTC by Anjugeorg-e

2023-02-14 18:24 UTC, APJ-9 requested changes

2023-02-14 18:24 UTC, APJ-9 commented on AzureOriginal/index.html
> +        <div class="space"> </div>
why there is a space class here?

2023-02-14 18:24 UTC, APJ-9 commented on AzureOriginal/style.css
> +        padding: 2px 0;
group similar styles

2023-02-14 18:24 UTC, APJ-9 commented on AzureOriginal/style.css
> +        padding-bottom: 42px;
Why 2 padding here?

2023-02-14 18:24 UTC, APJ-9 commented on AzureOriginal/style.css
> +        padding-left: 5%;
Why 2 kinds of padding here?

2023-02-14 18:24 UTC, APJ-9 commented on AzureOriginal/style.css
> +        margin-top: 3px;
Why 2 kinds of margins here?

2023-02-14 18:24 UTC, APJ-9 commented on AzureOriginal/style.css
> +        border: 0px solid transparent;
what is the purpose of this code `border: 0px solid transparent;`

2023-02-14 18:24 UTC, APJ-9 commented on AzureOriginal/style.css
> +        margin-left: 5%;
group similar styles

2023-02-14 18:27 UTC, APJ-9 reviewed
Add screen shots of all the view

2023-02-15 03:11 UTC, Anjugeorg-e commented on AzureOriginal/index.html
> +        <div class="space"> </div>
renamed to hybrid_box now

2023-02-15 03:13 UTC, Anjugeorg-e commented on AzureOriginal/style.css
> +        padding: 2px 0;
updated

2023-02-15 03:17 UTC, Anjugeorg-e commented on AzureOriginal/style.css
> +        padding-bottom: 42px;
updated to a single padding value

2023-02-15 03:19 UTC, Anjugeorg-e commented on AzureOriginal/style.css
> +        padding-left: 5%;
changed

2023-02-15 03:22 UTC, Anjugeorg-e commented on AzureOriginal/style.css
> +        margin-top: 3px;
updated to single margin value

2023-02-15 03:30 UTC, Anjugeorg-e commented on AzureOriginal/style.css
> +        border: 0px solid transparent;
removed now. i thought of adding a blue border in previous pixel once we hover over  that . now cleared all.

2023-02-15 03:59 UTC, Anjugeorg-e commented
![azure_mobileview](https://user-images.githubusercontent.com/114215424/218925109-ec2e07de-d256-4459-b5b9-59a99bb3df7e.png)
![azure_tablet](https://user-images.githubusercontent.com/114215424/218925643-2587a505-3c8c-432b-80ea-0d43d18961d6.png)
![azure_laptop](https://user-images.githubusercontent.com/114215424/218925706-3fccdd75-69f8-4898-b4f0-45496ffc8a6c.png)

2023-02-15 11:50 UTC, APJ-9 approved these changes

2023-02-15 11:50 UTC, merged